os:
  - osx
install:
  - curl -L -O http://mirrors.concertpass.com/tex-archive/systems/mac/mactex/BasicTeX.pkg
  - sudo installer -pkg BasicTeX.pkg -target /
  - rm BasicTeX.pkg
  - export PATH=$PATH:/usr/texbin
  - sudo tlmgr update --self --all
  - sudo tlmgr install collection-langjapanese collection-fontsrecommended
script:
  - make clean
  - make all
