os:
  - osx
  - linux
dist: trusty
sudo: required
before_install:
  - wget https://raw.githubusercontent.com/y-yu/install-tex-travis/master/install-tex.sh
  - wget https://raw.githubusercontent.com/y-yu/install-tex-travis/master/tlmgr.sh
  - chmod +x install-tex.sh tlmgr.sh
install:
  - . ./install-tex.sh
  - ./tlmgr.sh update --self --all
  - ./tlmgr.sh install collection-langjapanese collection-fontsrecommended
script:
  - make
  - rm -f *.dvi
  - fmtutil --byfmt platex
  - make all
